---
- name: Update Apache2 server config item
  lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
  notify: Restart apache2 systemd service
  ignore_errors: "{{ ansible_check_mode }}"
